# Generated by Django 4.2.6 on 2023-11-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_livromodel_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='livromodel',
            name='isbn',
            field=models.CharField(default='isbn', max_length=200, verbose_name='isbn'),
            preserve_default=False,
        ),
    ]
