# Generated by Django 4.2.6 on 2023-11-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_livromodel_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='livromodel',
            name='numPages',
            field=models.CharField(default='numPages', max_length=200, verbose_name='numPages'),
            preserve_default=False,
        ),
    ]
