# Generated by Django 4.2.6 on 2023-11-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_livromodel_numpages'),
    ]

    operations = [
        migrations.AddField(
            model_name='livromodel',
            name='anoEscrita',
            field=models.CharField(default='anoEscrita', max_length=200, verbose_name='anoEscrita'),
            preserve_default=False,
        ),
    ]
