# Generated by Django 4.2.6 on 2023-11-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_livromodel_anoescrita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livromodel',
            name='anoEscrita',
            field=models.CharField(max_length=4, verbose_name='anoEscrita'),
        ),
        migrations.AlterField(
            model_name='livromodel',
            name='isbn',
            field=models.CharField(max_length=13, verbose_name='isbn'),
        ),
        migrations.AlterField(
            model_name='livromodel',
            name='numPages',
            field=models.CharField(max_length=3, verbose_name='numPages'),
        ),
    ]
